#!/bin/zsh
# vim: set expandtab ts=2 sw=2 nowrap ft=sh ff=unix : */
set -e -u

uname=`uname`
case $uname in
  Darwin)
    fetch="curl"
    fetch_flags="-L"
    brew install python3
    ;;
  Linux)
    sudo aptitude install curl python3 # rvm uses curl
    fetch="curl"
    fetch_flags="-L"
    ;;
  FreeBSD)
    # TODO: Install python3
    fetch="fetch"
    fetch_flags="-o -"
    ;;
esac

# python
if [ ! -d ~/.pyvenv ]; then
  mkdir ~/.pyvenv
  if [ -f `which pyvenv-3.4` ]; then
    PYVENV=pyvenv-3.4
  else
    PYVENV=pyvenv-3.3
  fi
  # --without-pip for Ubuntu 14.04 LTS
  cd ~/.pyvenv; $PYVENV --without-pip py3
  echo 'PATH=$HOME/.pyvenv/py3/bin:$PATH' >> ~/.zshrc

  PATH=$HOME/.pyvenv/py3/bin:$PATH
  rehash
  curl -L http://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py | python
  rehash
  easy_install pip
  pip install ipython virtualenvwrapper

  echo 'WORKON_HOME=$HOME/.pyvenv/' >> ~/.zshrc
  echo '. $HOME/.pyvenv/py3/bin/virtualenvwrapper.sh' >> ~/.zshrc
  echo 'source $HOME/.pyvenv/py3/bin/activate' >> ~/.zshrc
fi

# ruby
if [ -d ~/.rvm ]; then
  rvm implode
fi

if [ ! -d ~/.rbenv ]; then
  git clone git://github.com/sstephenson/rbenv.git ~/.rbenv
  git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
  echo '[[ -s "${HOME}/.rbenv/bin/rbenv" ]] && export PATH="$HOME/.rbenv/bin:$PATH" && eval "$(rbenv init -)"' >> ~/.zshrc

  mkdir -p ~/.rbenv/plugins

  # rbenv-binstubs
  git clone https://github.com/ianheggie/rbenv-binstubs.git ~/.rbenv/plugins/rbenv-binstubs
  # rbenv-gemset
  git clone git://github.com/jf/rbenv-gemset.git ~/.rbenv/plugins/rbenv-gemset
  # rbenv-gem-rehash
  git clone https://github.com/sstephenson/rbenv-gem-rehash.git ~/.rbenv/plugins/rbenv-gem-rehash
fi

# perl
if [ ! -d ~/.perlbrew ]; then
  eval $fetch $fetch_flags http://install.perlbrew.pl/ | PERLBREW_ROOT=~/.perlbrew bash
  echo "export PERLBREW_ROOT=~/.perlbrew" >> ~/.zshrc
  echo '[[ -s "${HOME}/.perlbrew/etc/bashrc" ]] && source $HOME/.perlbrew/etc/bashrc' >> ~/.zshrc
fi

# Node.js
if [ ! -d ~/.nvm ]; then
  git clone git://github.com/creationix/nvm.git ~/.nvm
  echo '[[ -s "${HOME}/.nvm/nvm.sh" ]] && source $HOME/.nvm/nvm.sh' >> ~/.zshrc
fi

cat <<INSTRUCTION
Reload ~/.zshrc and execute anybrew-install

  $ source ~/.zshrc
  $ ./anybrew-install
INSTRUCTION
