#!/bin/zsh
# vim: set expandtab ts=2 sw=2 nowrap ft=sh ff=unix : */
set -e -u

# ruby
rbenv install 2.0.0-p247
echo 'gem: --no-ri --no-rdoc' >> ~/.gemrc # no document

# perl
perlbrew install -j 8 --notest perl-5.18.1 || echo
perlbrew switch perl-5.18.1
# perlbrew install-cpanm

# Node.js
. ~/.nvm/nvm.sh
nvm install v0.10.21
nvm alias default v0.10.21
