#!/bin/zsh
# vim: set expandtab ts=2 sw=2 nowrap ft=sh ff=unix : */
set -e -u

uname=`uname`
case $uname in
  Darwin)
    fetch="curl"
    fetch_flags="-L"
    brew install python3
    ;;
  Linux)
    sudo aptitude install curl python3 # rvm uses curl
    fetch="curl"
    fetch_flags="-L"
    ;;
  FreeBSD)
    # TODO: Install python3
    fetch="fetch"
    fetch_flags="-o -"
    ;;
esac

# python
if [ ! -d ~/.pyenv ]; then
  git clone https://github.com/yyuu/pyenv.git ~/.pyenv
  git clone git://github.com/yyuu/pyenv-virtualenv.git ~/.pyenv/plugins/pyenv-virtualenv
  cat <<EOF >> ~/.zshenv
export PYENV_ROOT="\${HOME}/.pyenv"
if [ -n \${PYENV_ROOT} ]; then
  path=(\${PYENV_ROOT}/bin \${PYENV_ROOT}/shims \${path})
fi
eval "\$(pyenv init -)"
EOF
fi

# ruby
if [ -d ~/.rvm ]; then
  rvm implode
fi

if [ ! -d ~/.rbenv ]; then
  git clone git://github.com/sstephenson/rbenv.git ~/.rbenv
  git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
  echo '[[ -s "${HOME}/.rbenv/bin/rbenv" ]] && export PATH="$HOME/.rbenv/bin:$PATH" && eval "$(rbenv init -)"' >> ~/.zshenv

  mkdir -p ~/.rbenv/plugins

  # rbenv-binstubs
  git clone https://github.com/ianheggie/rbenv-binstubs.git ~/.rbenv/plugins/rbenv-binstubs
  # rbenv-gemset
  git clone git://github.com/jf/rbenv-gemset.git ~/.rbenv/plugins/rbenv-gemset
  # rbenv-gem-rehash
  git clone https://github.com/sstephenson/rbenv-gem-rehash.git ~/.rbenv/plugins/rbenv-gem-rehash
fi

# perl
if [ ! -d ~/.perlbrew ]; then
  eval $fetch $fetch_flags http://install.perlbrew.pl/ | PERLBREW_ROOT=~/.perlbrew bash
  echo "export PERLBREW_ROOT=~/.perlbrew" >> ~/.zshenv
  echo '[[ -s "${HOME}/.perlbrew/etc/bashrc" ]] && source $HOME/.perlbrew/etc/bashrc' >> ~/.zshenv
fi

# Node.js
if [ ! -d ~/.nvm ]; then
  git clone git://github.com/creationix/nvm.git ~/.nvm
  echo '[[ -s "${HOME}/.nvm/nvm.sh" ]] && source $HOME/.nvm/nvm.sh' >> ~/.zshenv
fi

cat <<INSTRUCTION
Reload ~/.zshenv and execute anybrew-install

  $ source ~/.zshenv
  $ ./anybrew-install
INSTRUCTION
