#!/bin/zsh
# vim: set expandtab ts=2 sw=2 nowrap ft=sh ff=unix : */
set -e -u

# python
pythonbrew install 2.7.3
pythonbrew switch 2.7.3
pip install ipython # interactive shell
#pythonbrew venv create gunya -p 2.7.3
#pythonbrew venv use gunya

# ruby
rvm autolibs enable
rvm install 1.9.3
# rvm 1.9.3 do gem install pry # interactive shell
rvm 1.9.3 do rvm gemset create gunya
rvm 1.9.3 use 1.9.3@gunya --default
echo 'gem: --no-ri --no-rdoc' >> ~/.gemrc # no document

# perl
perlbrew install -j 8 --notest perl-5.10.1 || echo
perlbrew switch perl-5.10.1
# perlbrew install-cpanm

# Node.js
. ~/.nvm/nvm.sh
nvm install v0.10.12
nvm alias default v0.10.12
