#!/bin/sh
# vim: set expandtab ts=2 sw=2 nowrap ft=sh ff=unix : */
set -e -u

cwd=$(dirname $0)
base_dir=$(cd $cwd; pwd)

# bin
if [ ! -d ~/bin ]; then
  mkdir ~/bin
fi

for path in `ls -1 bin/*`
do
  ln -snf $base_dir/$path ~/$path
done

# zsh
if [ ! -d ~/.zsh ]; then
  mkdir ~/.zsh
  ln -snf $base_dir/zsh ~/.zsh/zsh
fi

# remove antigen
if [ -d ~/.zsh/antigen ]; then
  rm -rf ~/.zsh/antigen
fi

# remove zgen
if [ -d ~/.zsh/zgen ]; then
  rm -rf ~/.zsh/zgen
fi

# zplug
curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh| zsh

if ! grep -xFsq "source ~/.zsh/zsh/zshenv.index" ~/.zshenv; then
  cat <<EOF >> ~/.zshenv
source ~/.zsh/zsh/zshenv.index
EOF
fi

if ! grep -xFsq "source ~/.zsh/zsh/zshrc.index" ~/.zshrc; then
  cat <<EOF >> ~/.zshrc
source ~/.zsh/zsh/zshrc.index
EOF
fi

# git
ln -snf $base_dir/git/gitconfig ~/.gitconfig

# vim
ln -snf $base_dir/vim/vimrc ~/.vimrc
ln -snf $base_dir/vim/vim ~/.vim
