#!/bin/sh
# vim: set expandtab ts=2 sw=2 nowrap ft=sh ff=unix : */
set -e -u

cwd=$(dirname $0)
base_dir=$(cd $cwd; pwd)

# update submodules
git submodule init
git submodule update

# zsh
if [ ! -d ~/antigen ]; then
  git clone https://github.com/zsh-users/antigen.git ~/antigen
  echo "source ~/.zshrc.antigen" >> ~/.zshrc
  echo "export EDITOR=vim" >> ~/.zshrc
fi
ln -snf $base_dir/zsh/zshrc.antigen ~/.zshrc.antigen

# git
ln -snf $base_dir/git/gitconfig ~/.gitconfig

# vim
ln -snf $base_dir/vim/vimrc ~/.vimrc
ln -snf $base_dir/vim/vim ~/.vim
vim +NeoBundleInstall +qall
