#!/bin/zsh
# vim: set expandtab ts=2 sw=2 nowrap ft=sh ff=unix : */
set -e -u

go get github.com/motemen/gore
go get github.com/nsf/gocode
go get github.com/k0kubun/pp
go get github.com/rogpeppe/godef
go get github.com/jstemmer/gotags
go get github.com/golang/lint/golint
go get golang.org/x/tools/cmd/godoc
go get golang.org/x/tools/cmd/goimports
go get golang.org/x/tools/cmd/gorename
go get golang.org/x/tools/cmd/guru
