#!/bin/sh
# vim: set expandtab ts=2 sw=2 nowrap ft=sh ff=unix : */
set -u

uname=`uname`

# install basic module
case $uname in
  Darwin)
    # TODO: check whether Xcode is installed or not
    if ! command -v brew &> /dev/null; then
      echo "Install Homebrew first"
      open "https://brew.sh/"
      exit
    fi
    brew update
    brew install \
      vim \
      ffmpeg \
      git zsh \
      zlib openssl sqlite libxml2 libxslt \
      gdbm readline \
      bison libyaml ncurses \
      go \
      ghq peco \
      ripgrep rga \
      lsd \
      hstr \
      fd \
      coreutils bvi jq gron ngrep wrk bat autossh \
      tokei \ # Count your code, quickly
      direnv \
      starship \
      exiftool \
      imagemagick \
      rust \
      dust diskonaut \ # A more intuitive version of du in rust, Terminal disk space navigator
      stern k9s \ # Multi pod and container log tailing for Kubernetes, Kubernetes CLI To Manage Your Clusters In Style!
      dog \ # A command-line DNS client
      cheat navi tldr \ # Cheetsheets
      xsv \ # A command line program for indexing, slicing, analyzing, splitting and joining CSV files
      pastel \ # A command-line tool to generate, analyze, convert and manipulate colors
      youtube-dl yt-dlp \ # YouTube and other sites downloaders
      rclone \ # Rclone syncs your files to cloud storage
      xpdf \ # A free PDF viewer and toolkit, including a text extractor, image converter, HTML converter, and more.
      difftastic \ # A structural diff that understands syntax
      mise \ # dev tools, env vars, task runner
      dive \ # A tool for exploring a docker image, layer contents, and discovering ways to shrink the size of your Docker/OCI image
      eza \ # A modern, maintained replacement for ls
      xh \ # Friendly and fast tool for sending HTTP requests
      aicommits # A CLI that writes your git commit messages for you with AI
    brew install --cask fig mpv wezterm visual-studio-code
    ;;
  Linux)
    if [ -f /etc/debian_version ]; then
      sudo apt-get update
      sudo apt-get install aptitude
      sudo aptitude install \
        build-essential git zsh curl file sudo vim \
        zlib1g-dev libssl-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev \
        libgdbm-dev libbz2-dev libreadline-dev \
        bison libreadline6-dev libyaml-dev libncurses5-dev \
        bvi jq gron ngrep autossh \
        direnv \
        imagemagick \
        ripgrep \
        rclone \
        mpv
      sudo aptitude install language-pack-en language-pack-ja || echo "not found language packs"

      if [ ! -d /home/linuxbrew ]; then
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> $HOME/.zprofile
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
      fi
      eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
      brew update
      ulimit -n 4096 # ffmpeg installs many packages so we need many file descriptors
      brew install \
        ffmpeg \
        ghq peco \
        fig \
        jq autossh \
        direnv \
        imagemagick \
        ripgrep
    elif [ -f /etc/redhat-release ]; then
      sudo yum update
      sudo yum groupinstall "Development Tools"
      sudo yum install git zsh
    fi
    sh -c "$(curl -fsSL https://starship.rs/install.sh)"
    ;;
  FreeBSD)
    echo "To be implemented"
    exit 1
    ;;
esac
