#!/bin/sh
# vim: set expandtab ts=2 sw=2 nowrap ft=sh ff=unix : */
set -e -u

uname=`uname`

# install basic module
case $uname in
  Darwin)
    # TODO: check whether Xcode is installed or not
    if [ ! -d /usr/local/Cellar ]; then
      ruby -e "$(curl -fsSkL raw.github.com/mxcl/homebrew/go)"
    fi
    brew update
    brew install \
      git zsh vim \
      zlib openssl sqlite libxml2 libxslt \
      gdbm readline \
      bison libyaml ncurses \
      go
    # prevent scroll animation in iTerm2
    defaults write com.googlecode.iterm2 NSScrollAnimationEnabled -bool NO
    # Don't use ambiguous double width in iTerm2
    /usr/libexec/PlistBuddy -c \
      "Set :\"New Bookmarks\":0:\"Ambiguous Double Width\" false" \
      ~/Library/Preferences/com.googlecode.iterm2.plist
    # Install vim powerline fonts
    git clone --depth 1 https://github.com/powerline/fonts.git
    (cd fonts && ./install.sh)
    rm -rf fonts
    # Set Powerline fonts
    /usr/libexec/PlistBuddy -c \
      "Set :\"New Bookmarks\":0:\"Normal Font\" \"MesloLGM-RegularForPowerline 12\"" \
      ~/Library/Preferences/com.googlecode.iterm2.plist
    /usr/libexec/PlistBuddy -c \
      "Set :\"New Bookmarks\":0:\"Non Ascii Font\" \"MesloLGM-RegularForPowerline 12\"" \
      ~/Library/Preferences/com.googlecode.iterm2.plist
    # Install color schemas
    set +e
    /usr/libexec/PlistBuddy -c \
      "Add :'Custom Color Presets':'Cobalt2' dict" \
      ~/Library/Preferences/com.googlecode.iterm2.plist
    /usr/libexec/PlistBuddy -c \
      "Merge 'iTerm2/Cobalt2.itermcolors' :'Custom Color Presets':'Cobalt2'" \
      ~/Library/Preferences/com.googlecode.iterm2.plist
    /usr/libexec/PlistBuddy -c \
      "Add :'Custom Color Presets':'Tomorrow Night Bright' dict" \
      ~/Library/Preferences/com.googlecode.iterm2.plist
    /usr/libexec/PlistBuddy -c \
      "Merge 'iTerm2/Tomorrow Night Bright.itermcolors' :'Custom Color Presets':'Tomorrow Night Bright'" \
      ~/Library/Preferences/com.googlecode.iterm2.plist
    /usr/libexec/PlistBuddy -c \
      "Add :'Custom Color Presets':'Tomorrow Night Blue' dict" \
      ~/Library/Preferences/com.googlecode.iterm2.plist
    /usr/libexec/PlistBuddy -c \
      "Merge 'iTerm2/Tomorrow Night Blue.itermcolors' :'Custom Color Presets':'Tomorrow Night Blue'" \
      ~/Library/Preferences/com.googlecode.iterm2.plist
    set -e
    ;;
  Linux)
    if [ -f /etc/debian_version ]; then
      sudo apt-get update
      sudo apt-get install aptitude
      sudo aptitude install language-pack-en language-pack-ja
      sudo aptitude install build-essential git zsh curl sudo vim
      # For building some language
      sudo aptitude install zlib1g-dev libssl-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev
      # For building Python
      sudo aptitude install libgdbm-dev libbz2-dev libreadline-dev
      # For bulding Ruby
      sudo aptitude install bison libreadline6-dev libyaml-dev libncurses5-dev
    elif [ -f /etc/redhat-release ]; then
      sudo yum update
      sudo yum groupinstall "Development Tools"
      sudo yum install git zsh
    fi
    ;;
  FreeBSD)
    echo "To be implemented"
    exit 1
    ;;
esac
