#!/bin/sh
# vim: set expandtab ts=2 sw=2 nowrap ft=sh ff=unix : */
set -u

uname=`uname`

# install basic module
case $uname in
  Darwin)
    # TODO: check whether Xcode is installed or not
    # TODO: Use Brewfile ref.) https://www.karakaram.com/how-to-automate-your-mac-set-up
    if [ ! -d /usr/local/Homebrew ]; then
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      echo 'eval "$(/usr/local/bin/brew shellenv)"' >> $HOME/.zprofile
    fi
    eval "$(/usr/local/bin/brew shellenv)"
    brew update
    brew install \
      vim \
      ffmpeg \
      git zsh \
      zlib openssl sqlite libxml2 libxslt \
      gdbm readline \
      bison libyaml ncurses \
      go \
      ghq peco \
      ripgrep rga \
      fd \
      coreutils bvi jq gron ngrep wrk bat autossh \
      tokei \
      direnv jenv \
      starship \
      git-delta \
      imagemagick \
      rust \
      dust diskonaut \
      stern k9s \
      dog \
      cheat navi tldr \
      xsv \
      pastel \
      youtube-dl yt-dlp \
      rclone \
      mpv
    ;;
  Linux)
    if [ -f /etc/debian_version ]; then
      sudo apt-get update
      sudo apt-get install aptitude
      sudo aptitude install \
        build-essential git zsh curl sudo vim \
        zlib1g-dev libssl-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev \
        libgdbm-dev libbz2-dev libreadline-dev \
        bison libreadline6-dev libyaml-dev libncurses5-dev \
        bvi jq gron ngrep autossh \
        direnv jenv \
        starship \
        imagemagick \
        ripgrep \
        rclone \
        mpv
      sudo aptitude install language-pack-en language-pack-ja || echo "not found language packs"
      # TODO: install fd/wrk/bat
      # TODO: install tokei
      # TODO: install git-delta
      # TODO: install cheat/navi/tldr
      # TODO: install dust/diskonaut
      # TODO: install xsv
      # TODO: install pastel
      # TODO: install rga (ripgrep-all)
    elif [ -f /etc/redhat-release ]; then
      sudo yum update
      sudo yum groupinstall "Development Tools"
      sudo yum install git zsh
    fi
    ;;
  FreeBSD)
    echo "To be implemented"
    exit 1
    ;;
esac
