#!/bin/zsh
# vim: set expandtab ts=2 sw=2 nowrap ft=sh ff=unix : */
set -e -u

uname=`uname`
case $uname in
  Darwin)
    fetch="curl"
    fetch_flags="-L"
    brew install python3
    ;;
  Linux)
    sudo aptitude install curl python3 # rvm uses curl
    fetch="curl"
    fetch_flags="-L"
    ;;
  FreeBSD)
    # TODO: Install python3
    fetch="fetch"
    fetch_flags="-o -"
    ;;
esac

# python
if [ ! -d ~/.pyenv ]; then
  git clone git://github.com/yyuu/pyenv.git ~/.pyenv
  git clone git://github.com/yyuu/pyenv-virtualenv.git ~/.pyenv/plugins/pyenv-virtualenv
fi

# ruby
if [ ! -d ~/.rbenv ]; then
  git clone git://github.com/sstephenson/rbenv.git ~/.rbenv
  git clone git://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build

  mkdir -p ~/.rbenv/plugins

  # rbenv-binstubs
  git clone git://github.com/ianheggie/rbenv-binstubs.git ~/.rbenv/plugins/rbenv-binstubs
  # rbenv-gemset
  git clone git://github.com/jf/rbenv-gemset.git ~/.rbenv/plugins/rbenv-gemset
  # rbenv-gem-rehash
  git clone git://github.com/sstephenson/rbenv-gem-rehash.git ~/.rbenv/plugins/rbenv-gem-rehash
fi
# good bye rvm
if [ -d ~/.rvm ]; then
  rvm implode
fi

# perl
if [ ! -d ~/.plenv ]; then
  git clone git://github.com/tokuhirom/plenv.git ~/.plenv
fi
if [ ! -d ~/.plenv/plugings/perl-build ]; then
  git clone https://github.com/tokuhirom/Perl-Build.git ~/.plenv/plugins/perl-build/
fi
# good bye perlbrew
if [ -d ~/.perlbrew ]; then
  rm -rf ~/.perlbrew
fi

# Node.js
if [ ! -d ~/.nodenv ]; then
  git clone git://github.com/nodenv/nodenv.git ~/.nodenv
fi
# good bye nvm
if [ -d ~/.nvm ]; then
  rm -rf ~/.nvm
fi

cat <<INSTRUCTION
Reload shell execute langenv-install
INSTRUCTION
