#!/bin/zsh
# vim: set expandtab ts=2 sw=2 nowrap ft=sh ff=unix : */
set -e -u

export PATH=~/.pyenv/bin:~/.rbenv/bin:~/.plenv/bin:~/.nodenv/bin:${PATH}

# Python
(cd ~/.pyenv && git pull)

PYTHON_CONFIGURE_OPTS="--enable-shared"
if [ ! -d ~/.pyenv/versions/3.9.10 ]; then
  pyenv install 3.9.10
fi
pyenv rehash

# ruby
(cd ~/.rbenv && git pull)
(cd ~/.rbenv/plugins/ruby-build && git pull)
if [ ! -d ~/.rbenv/versions/3.0.3 ]; then
  rbenv install 3.0.3
fi
echo 'gem: --no-ri --no-rdoc' >> ~/.gemrc # no document
rbenv rehash

# Node.js
(cd ~/.nodenv && git pull)
(cd ~/.nodenv/plugins/node-build && git pull)
if [ ! -d ~/.nodenv/versions/16.13.2 ]; then
  nodenv install 16.13.2
fi
nodenv rehash
