#!/bin/zsh
# vim: set expandtab ts=2 sw=2 nowrap ft=sh ff=unix : */
set -e -u

export PATH=~/.pyenv/bin:~/.rbenv/bin:~/.plenv/bin:~/.nodenv/bin:${PATH}

# Python
(cd ~/.pyenv && git pull)

PYTHON_CONFIGURE_OPTS="--enable-shared"
if [ ! -d ~/.pyenv/versions/2.7.16 ]; then
  pyenv install 2.7.16
fi
if [ ! -d ~/.pyenv/versions/3.7.2 ]; then
  pyenv install 3.7.2
fi
pyenv rehash

# ruby
(cd ~/.rbenv && git pull)
(cd ~/.rbenv/plugins/ruby-build && git pull)
if [ ! -d ~/.rbenv/versions/2.6.1 ]; then
  rbenv install 2.6.1
fi
echo 'gem: --no-ri --no-rdoc' >> ~/.gemrc # no document
rbenv rehash

# perl
(cd ~/.plenv && git pull)
(cd ~/.plenv/plugins/perl-build && git pull)
if [ ! -d ~/.plenv/versions/5.28.1 ]; then
  plenv install 5.28.1
  plenv global 5.28.1
  plenv install-cpanm
fi

# Node.js
(cd ~/.nodenv && git pull)
(cd ~/.nodenv/plugins/node-build && git pull)
if [ ! -d ~/.nodenv/versions/10.15.3 ]; then
  nodenv install 10.15.3
fi
