#!/bin/zsh
# vim: set expandtab ts=2 sw=2 nowrap ft=sh ff=unix : */
set -e -u

mise install python@3.11
mise use --global python@3.11
curl -sSf https://rye-up.com/get | bash
mise install ruby@3.2
mise use --global ruby@3.2
mise install nodejs@lts
mise use --global nodejs@lts
