set nocompatible
filetype off

let s:dein_dir = expand('~/.vim/dein')
let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'

if &runtimepath !~# '/dein.vim'
  if !isdirectory(s:dein_repo_dir)
    execute '!git clone https://github.com/Shougo/dein.vim' s:dein_repo_dir
  endif
  execute 'set runtimepath^=' . fnamemodify(s:dein_repo_dir, ':p')
endif

call dein#begin(s:dein_dir)

let s:toml      = '~/.vim/rc/dein.toml'
let s:lazy_toml = '~/.vim/rc/dein_lazy.toml'

if dein#load_cache([expand('<sfile>'), s:toml, s:lazy_toml])
  call dein#load_toml(s:toml,      {'lazy': 0})
  call dein#load_toml(s:lazy_toml, {'lazy': 1})
  call dein#save_cache()
endif

call dein#end()

if dein#check_install()
  call dein#install()
endif

" after dein
filetype plugin indent on
syntax enable

" color
set t_Co=256
colorscheme gunya

" encoding
set enc=utf-8
set fenc=utf-8
set fencs=utf-8,euc-jp,cp932
set fileformats=unix,dos

" backspace
set backspace=indent,eol,start

" tab
set expandtab
set smartindent
set tabstop=2
set softtabstop=2
set shiftwidth=2
set smarttab

" scroll
set scroll=11

" find
set hlsearch
set ignorecase
set smartcase
set incsearch
set wrapscan

" status line
set laststatus=2

" show
set showcmd
set showmode
set showmatch
set matchtime=2

" misc
set number
set ruler
set ttyfast
set list
set listchars=tab:▸\ ,eol:¬
set wildmode=list:longest,full
set display=lastline

" map
nnoremap Y y$

" backup
set nobackup
set swapfile

" bell
set visualbell

" modeline
set modeline
set modelines=5

" vim-airline
" NOTE: Requires patched font.
"       https://github.com/powerline/fonts
let g:airline_powerline_fonts = 1
" vim-arline END

" For Mac scroll
nnoremap <PageDown> <C-F>
nnoremap <PageUp> <C-B>

" matchit/hi_matchit
source $VIMRUNTIME/macros/matchit.vim
let g:hl_matchit_enable_on_vim_startup = 1
let g:hl_matchit_hl_groupname = 'Search'
"let g:hl_matchit_allow_ft = 'html\|vim\|ruby\|sh'
