[[plugins]]
repo = 'Shougo/dein.vim'

# EditorConfig
[[plugins]]
repo = 'editorconfig/editorconfig-vim'

# show & delete trailing space
[[plugins]]
repo = 'csexton/trailertrash.vim'

# Auto close
[[plugins]]
repo = 'vim-scripts/AutoClose'

# vim-airline
[[plugins]]
repo = 'vim-airline/vim-airline'
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# relative move with "'k"
[[plugins]]
repo = 'Lokaltog/vim-easymotion'

# git
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'gregsexton/gitv'

# highlight matchit
[[plugins]]
repo = "vimtaku/hl_matchit.vim"

# quick run with <Leader>r
[[plugins]]
repo = 'thinca/vim-quickrun'

# show errormarker
[[plugins]]
repo = 'vim-scripts/errormarker.vim'

# toggle comment with ',,'
[[plugins]]
repo = 'scrooloose/nerdcommenter'

# show vimshell as window
[[plugins]]
repo = 'Shougo/vimshell'

# edit surrounded texts
[[plugins]]
repo = 'vim-scripts/surround.vim'

# comment out with '\\'
[[plugins]]
repo = 'tpope/vim-commentary'

# handle lines with same indent spaces as text object with 'ai'/'ii'
[[plugins]]
repo = 'kana/vim-textobj-user'
[[plugins]]
repo = 'kana/vim-textobj-indent'
