[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['unite.vim']

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']

# Markdown
[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['markdown']

[[plugins]]
repo = 'kannokanno/previm'
depends = ['open-browser.vim']
on_ft = ['markdown']
hook_source = ''' " {{{
    " Disable folding
    let g:vim_markdown_folding_disabled = 1
''' # }}}

[[plugins]]
repo = 'joker1007/vim-markdown-quote-syntax'
on_ft = ['markdown']

# go
repo = 'fatih/vim-go'
on_ft = ['go']
hook_source = ''' " {{{
    let g:go_fmt_autosave = 1
    let g:syntastic_go_checkers = ['go', 'govet', 'errcheck']
    let g:syntastic_aggregate_errors = 1
''' # }}}

repo = 'dgryski/vim-godef'
on_ft = ['go']
hook_source = '''
  let g:godef_split = 2
'''

# rust
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']
build = 'cargo install rustfmt'
hook_source = '''
  let g:rustfmt_autosave = 1
  let g:rustfmt_command = '$HOME/.cargo/bin/rustfmt'
'''

[[plugins]]
repo = 'racer-rust/vim-racer'
on_ft = ['rust']
build = 'cargo install racer'
hook_source = '''
  set hidden
  let g:racer_cmd = '$HOME/.cargo/bin/racer'
'''

# rails
[[plugins]]
repo = 'tpope/vim-rails'

# toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

# yaml
[[plugins]]
repo = 'chase/vim-ansible-yaml'
on_ft = ['yaml']

# llvm ir
[[plugins]]
repo = 'qnighy/llvm.vim'
on_ft = ['llvm']

# html5
[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

# css color
[[plugins]]
repo = 'ap/vim-css-color'
on_ft = ['css', 'less', 'sass']

# typescript
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript', 'typescript.tsx']

# typescript with React
[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
depends = ['typescript-vim']
on_ft = ['typescript', 'typescript.tsx']
