[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['unite.vim']

# Markdown
[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['markdown']

[[plugins]]
repo = 'kannokanno/previm'
depends = ['open-browser.vim']
on_ft = ['markdown']
hook_source = ''' " {{{
    " Disable folding
    let g:vim_markdown_folding_disabled = 1
''' # }}}

[[plugins]]
repo = 'joker1007/vim-markdown-quote-syntax'
on_ft = ['markdown']

# toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

# yaml
[[plugins]]
repo = 'chase/vim-ansible-yaml'
on_ft = ['yaml']

# html5
[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

# css color
[[plugins]]
repo = 'ap/vim-css-color'
on_ft = ['css', 'less', 'sass']

# css syntax
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css', 'less', 'sass']

# typescript
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript', 'typescriptreact']

# javascript
[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript', 'javascriptreact']

[[plugins]]
repo = 'othree/es.next.syntax.vim'
on_ft = ['javascript', 'javascriptreact']

[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'
on_ft = ['javascript', 'javascriptreact', 'typescript', 'typescriptreact']

# jsx/tsx
[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascript', 'javascriptreact', 'typescript', 'typescriptreact']
